# 高效航班排名系统配置文件 - 性能优化版
# 主要优化：
# 1. 启用全量数据训练模式以获得最佳性能
# 2. 优化模型参数以提升训练速度
# 3. 简化数据处理流程
# 4. 减少不必要的验证和检查

# 路径配置
paths:
  data_dir: "data/aeroclub-recsys-2025"
  model_input_dir: "data/aeroclub-recsys-2025/processed"
  model_save_dir: "data/aeroclub-recsys-2025/models"
  output_dir: "data/aeroclub-recsys-2025/submissions"
  log_dir: "logs"

# 数据处理配置 - 高效版
data_processing:
  chunk_size: 500000          # 增大块大小提升处理效率
  n_processes: 4              # 适中的进程数，避免过度并行开销
  force_encode: false
  force_segment: false
  force_feature: false
  verify_results: false       # 跳过验证以提升速度
  force_reprocess: false
  
  # 简化数据模式
  data_mode:
    mode: 'segments'          # 使用分段模式以保持兼容性
    
  # 内存优化
  memory_optimization:
    enable_memory_mapping: false     # 禁用内存映射减少开销
    enable_data_compression: false   # 禁用压缩减少CPU开销
    chunk_processing: true           # 启用分块处理

# 高效训练配置
training:
  segments: [0, 1, 2]
  
  # 重点优化的模型列表
  model_names: ['XGBRanker']
  
  use_gpu: true
  random_state: 42
  
  # 关键优化：启用全量数据训练
  use_full_data: true
  
  # 全量数据配置 - 针对XGBoost等快速训练优化
  full_data_config:
    enable_sampling: false           # 禁用采样，使用全部数据
    pytorch_epochs: 10              # 减少深度学习模型训练轮次
    pytorch_batch_size: 2048        # 大批次提升GPU利用率
    
    # 内存优化 - 简化
    memory_optimization:
      enable_memory_mapping: false
      enable_data_compression: false
      chunk_processing: true
      chunk_size: 100000
  
  # 简化数据集划分策略
  auto_split_strategy:
    thresholds:
      10000: 5     # 简化阈值，快速划分
      99999999: 10 # 大数据使用10折
    
    validation_size_strategy:
      default_val_size: 0.2
      large_data_val_size: 0.1
  
  # 优化的模型参数配置 - 专注于训练速度
  model_configs:
    XGBRanker:
      n_estimators: 100        # 适中的树数量
      max_depth: 6             # 适中的深度
      learning_rate: 0.1       # 较高的学习率加快收敛
      subsample: 0.8
      colsample_bytree: 0.8
      verbosity: 0             # 静默模式
      n_jobs: -1               # 使用所有CPU核心
      tree_method: 'hist'      # 使用直方图算法提升速度
      
    LGBMRanker:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      verbose: -1              # 静默模式
      n_jobs: -1
      force_col_wise: true     # 强制列方向处理提升速度
      
    LambdaMART:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      verbosity: 0
      n_jobs: -1
      tree_method: 'hist'
      
    # 简化的深度学习模型配置
    RankNet:
      hidden_dims: [128, 64]   # 减少网络复杂度
      learning_rate: 0.001
      epochs: 10               # 减少训练轮次
      batch_size: 256
      dropout_rate: 0.2
      
    NeuralRanker:
      hidden_units: [256, 128] # 简化网络结构
      learning_rate: 0.001
      epochs: 10
      batch_size: 128
      dropout_rate: 0.2
      
    TransformerRanker:
      num_heads: 4
      num_layers: 1            # 减少层数提升速度
      d_model: 64
      learning_rate: 0.001
      epochs: 8                # 减少训练轮次
      batch_size: 128

# 预测配置 - 高效版
prediction:
  segments: [0, 1, 2]
  model_names: ['XGBRanker']
  use_gpu: true
  enable_business_rules: false
  
  # 预测优化
  prediction_optimization:
    batch_size: 20000          # 增大批次提升预测效率
    memory_efficient: true
    cache_predictions: false   # 禁用缓存减少内存占用

# 流水线配置 - 高效版
pipeline:
  run_data_processing: false   # 跳过数据处理，假设数据已准备好
  run_training: true
  run_prediction: true
  
  # 执行模式
  execution_mode:
    mode: 'sequential'         # 顺序执行，避免并行开销
    
    # 简化并行策略
    parallel_strategy:
      auto_parallel: false     # 禁用自动并行
      max_workers: 1           # 单进程执行
      
    # 全量数据流水线配置
    full_data_pipeline:
      enable_checkpoints: false      # 禁用检查点减少IO开销
      enable_resume: false           # 禁用断点续训
      cleanup_temp_files: true       # 启用临时文件清理

# 性能监控配置 - 简化版
monitoring:
  enabled: false               # 禁用监控减少开销
  
  # 简化阈值
  thresholds:
    max_training_time: 7200    # 2小时训练时间限制
    max_memory_usage: 16384    # 16GB内存限制

# 日志配置 - 高效版
logging:
  level: "INFO"
  format: "%(asctime)s | %(levelname)8s | %(message)s"
  
  # 简化日志选项
  detailed_logging:
    model_training: true
    data_processing: false     # 禁用数据处理详细日志
    memory_monitoring: false   # 禁用内存监控日志
    performance_metrics: false # 禁用性能指标日志
    
  # 禁用日志轮转减少IO开销
  rotation:
    enabled: false

# 环境配置 - 高效版
environment:
  # 资源限制 - 适中配置
  resource_limits:
    max_memory_gb: 16
    max_cpu_cores: 8
    max_gpu_memory_gb: 8
    
  # 优化设置
  optimization:
    enable_mixed_precision: false   # 禁用混合精度减少复杂度
    enable_gradient_clipping: false # 禁用梯度裁剪
    enable_early_stopping: false   # 禁用早停，确保完整训练
    
  # 调试模式 - 全部禁用
  debug:
    enabled: false
    save_intermediate_data: false
    profile_memory: false
    profile_cpu: false

# 新增：快速模式配置
fast_mode:
  enabled: true
  
  # 快速启动设置
  quick_startup:
    skip_gpu_warmup: false         # 保留GPU预热以获得最佳性能
    skip_dependency_check: true    # 跳过依赖检查
    skip_data_validation: true     # 跳过数据验证
    minimal_logging: true          # 最小化日志
  
  # 训练加速设置
  training_acceleration:
    use_fast_trainer: true         # 使用快速训练器
    batch_training: true           # 批量训练
    skip_validation_split: true    # 跳过验证集划分（全量数据模式下）
    parallel_model_training: false # 禁用并行模型训练，避免资源竞争
  
  # 内存管理
  memory_management:
    aggressive_gc: true            # 积极垃圾回收
    clear_cache_frequently: true   # 频繁清理缓存
    minimal_data_copies: true      # 最小化数据拷贝