# 航班排名系统配置文件: Flight Ranking System Configuration

# 智能并行策略说明:
# - GPU可用时: 使用单进程+GPU加速，避免GPU竞争
# - GPU不可用时: 使用CPU多进程加速运算

# 路径配置
paths:
  data_dir: "data/aeroclub-recsys-2025"
  model_input_dir: "data/aeroclub-recsys-2025/segmented"
  model_save_dir: "data/aeroclub-recsys-2025/models"
  output_dir: "data/aeroclub-recsys-2025/submissions"
  log_dir: "logs"


# 数据处理配置
data_processing:
  chunk_size: 200000
  n_processes: null  # null=自动检测CPU核数
  force_encode: false
  force_segment: false
  force_feature: false
  verify_results: true
  force_reprocess: false

# 训练配置
training:
  segments: [0, 1, 2]
  model_names: ['XGBRanker', 'LGBMRanker', 'RankNet']
  use_gpu: true
  enable_parallel: true      # GPU模式下自动串行，CPU模式下并行
  enable_optimization: false  # 超参数优化
  n_folds: 8
  random_state: 42
  
  # 模型参数
  model_configs:
    XGBRanker:
      n_estimators: 200
      max_depth: 8
      learning_rate: 0.05
    
    LGBMRanker:
      n_estimators: 200
      max_depth: 8
      learning_rate: 0.05
    
    RankNet:
      hidden_dims: [128, 64, 32]
      learning_rate: 0.001
      dropout_rate: 0.2
    
    TransformerRanker:
      d_model: 128
      nhead: 8
      num_layers: 3
      learning_rate: 0.001

# 预测配置
prediction:
  segments: [0, 1, 2]
  model_names: ['XGBRanker', 'LGBMRanker', 'RankNet']
  use_gpu: true
  enable_parallel: true
  enable_business_rules: false
  
  # 集成权重 (可选)
  ensemble_weights:
    XGBRanker: 0.4
    LGBMRanker: 0.4
    RankNet: 0.2

# 流水线配置
pipeline:
  run_data_processing: true
  run_training: true
  run_prediction: true

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s | %(levelname)8s | %(name)s | %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
